---
# tasks file for apigee-opdk-setup-bootstrap
- name: Update bootstrap cache with key and value
  cache:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
  - { key: "apigeerepobasepath", value: "{{ apigeerepobasepath }}" }
  - { key: 'apigee_service', value: '{{ apigee_service }}' }
  - { key: 'apigee_setup', value: '{{ apigee_setup }}' }
  - { key: 'apigee_update', value: '{{ apigee_update }}' }
  - { key: 'apigee_all', value: '{{ apigee_all }}' }
  - { key: 'opdk_installer_path', value: '{{ opdk_installer_path }}' }
  - { key: 'opdk_license_target_file_path', value: "{{ opdk_license_target_file_path }}" }
  - { key: 'opdk_license_source_file_name', value: "{{ opdk_license_source_file_name }}" }
  - { key: 'default_apigee_repo_user', value: '{{ default_apigee_repo_user }}' }
  - { key: 'default_apigee_repo_password', value: '{{ default_apigee_repo_password}}' }
  - { key: 'default_apigee_repo_uri', value: '{{ default_apigee_repo_uri }}' }
  - { key: 'default_apigee_repo_protocol', value: '{{ default_apigee_repo_protocol }}' }
  - { key: 'default_apigee_repo_url', value: '{{ default_apigee_repo_url }}' }
